services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.4
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      
      # Habilitar m贸dulos API-based
      ENABLE_API_BASED_MODULES: 'true'
      
      # Configurar m贸dulos de Ollama
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      
      # Configuraci贸n para text2vec-ollama
      TEXT2VEC_OLLAMA_DEFAULT_OLLAMA_ENDPOINT: 'http://ollama:11434'
      
      # Configuraci贸n para generative-ollama  
      GENERATIVE_OLLAMA_DEFAULT_OLLAMA_ENDPOINT: 'http://ollama:11434'
      
      CLUSTER_HOSTNAME: 'node1'
    depends_on:
      - ollama
    
  ollama:
    # Use the official latest image
    image: ollama/ollama:latest
    # Define the container name for easy management
    container_name: ollama
    # Set the restart policy: container restarts automatically unless manually stopped
    restart: unless-stopped
    environment:
      # Configure allowed origins for accessing the Ollama API. '*' allows all origins.
      # Note: For security reasons, specify concrete domains or IP addresses in production or security-sensitive scenarios. I use '*' here for convenience with LobeChat.
      - OLLAMA_ORIGINS=*
    ports:
      # Map the host machine's port 11434 to the container's port 11434
      - "11434:11434"
    volumes:
      # Mount the host machine's ~/.ollama/data directory to the container's /root/.ollama directory
      # This is where Ollama stores model files and metadata, enabling persistent storage.
      - ~/.ollama/data:/root/.ollama
    deploy:
      # --- Resource Deployment Configuration Section ---
      resources:
        reservations:
          # GPU resource reservation configuration (Enable only if needed and an NVIDIA GPU is configured)
          devices:
            # Specify using the nvidia driver
            - driver: nvidia
              # Use all detected NVIDIA GPUs
              count: all
              # Request GPU capabilities
              capabilities: [gpu]
      # --- End of GPU Configuration Section ---